name: Substack to Instapaper

on:
  schedule:
    - cron: "30 10 * * *"  # 6:30 AM EST
    - cron: "30 11 * * *"  # 7:30 AM EST
    - cron: "30 12 * * *"  # 8:30 AM EST
    - cron: "30 13 * * *"  # 9:30 AM EST
    - cron: "30 14 * * *" # 10:30 AM EST
  workflow_dispatch:        # allows manual runs from GitHub

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run sync
        env:
          INSTAPAPER_USERNAME: ${{ secrets.INSTAPAPER_USERNAME }}
          INSTAPAPER_PASSWORD: ${{ secrets.INSTAPAPER_PASSWORD }}
          GMAIL_TOKEN: ${{ secrets.GMAIL_TOKEN }}
          GMAIL_CREDENTIALS: ${{ secrets.GMAIL_CREDENTIALS }}
        run: python main.py